---
- hosts: localhost

  tasks:
    - name: Road User
      shell: cat /tmp/userlist
      register: username

    - name: Add User
      user:
        name: "{{ item }}"
        password: "{{ item | password_hash('sha512') }}"
        update_password: on_create
      with_items: "{{ username.stdout_lines }}"

    - name: Add Wheel
      shell: usermod -G wheel "{{ item }}"
      with_items: "{{ username.stdout_lines }}"

---
- hosts: windows

  tasks:
    - name: Road User
      win_shell: Get-ContentC:\Work\userlist
      register: username

    - name: Add User
      win_user:
        name: "{{ item }}"
        password: "{{ item | password_hash('sha512') }}"
        groups:
        - Administrators
      with_items: "{{ username.stdout_lines }}"

