---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Road User
      shell: cat /tmp/adduserlist_m
      register: username

    - name: Add User
      user:
        name: "{{ item }}"
        groups: wheel
        password: "{{ item | password_hash('sha512') }}"
        update_password: on_create
      with_items: "{{ username.stdout_lines }}"
