---
- name: inst firewalld
  yum:
    name: firewalld
    state: latest

- name: start firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: fire conf
  firewalld:
    state: enabled
    immediate: true
    permanent: true
    service: "{{ firewall_service }}"
