---
# tasks file for myapache
#
- name: install apache package
  yum:
    name: httpd
    state: latest

- name: inst fire
  yum:
    name: firewalld
    state: latest

- name: temp file
  template:
    src: apache_httpdconf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0444
  notify:
    - restart apache

- name: temp index
  template:
    src: apache_indexhtml.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0444
  when: apache_enable

- name: start httpd daemon
  service:
    name: httpd
    state: started
    enabled: true
  when: apache_enable

- name: start firewalld daemon
  service:
    name: firewalld
    state: started
    enabled: true
  when: apache_enable

- name: open fire
  firewalld:
    port: 80/tcp
    immediate: true
    permanent: true
    state: enabled
  when: apache_enable

