---
- name: Install facts
  hosts: webserver
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact

  tasks:
    - name: Create
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: Install
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
