---
- name: ins lamp
  hosts: lamp
  vars:
    firewall: firewalld

  tasks:
    - name: Include yaml
      include_vars: vars/main.yml

    - name: envdd
      include: tasks/main.yml 

    - name: Instakll firewall
      yum:
        name: "{{ firewall }}"
        state: latest

    - name: Start firewall
      service:
        name: "{{ firewall }}"
        state: started
        enabled: true

    - name: open
      firewalld:
        service: http
        immediate: true
        permanent: true
        state: enabled

    - name: Crate
      copy:
        content: "{{ ansible_fqdn }}({{ ansible_default_ipv4.address }}) has been customized by Ansible\n"
        dest: "{{ web_root }}/index.html"
