---
- name: Con webserver
  hosts: lamp
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact

  tasks:
    - name: create
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"

    - name: install
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir}}"
