---
- hosts: databases
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - name: check
      command: date
      register: command_result
      changed_when: false

    - name: time
      debug:
        var: command_result["stdout"]

    - block:
      - name: install {{ web_package }}
        yum:
          name: "{{ web_package }}"
          state: latest
        failed_when: web_package == "httpd"

      rescue:
      - name: install {{ db_package }}
        yum:
          name: "{{ db_package }}"
          state: latest
     
      always:
        - name: start {{ db_service }}
          service:
            name: "{{ db_service }}"
            state: started
